[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = false

# ### Dark mode
# [colors.normal]
# black = "#333333"
# red = "#868686"
# green = "#a4a4a4"
# yellow = "#9a9a9a"
# blue = "#b8b8b8"
# magenta = "#c2c2c2"
# cyan = "#aeaeae"
# white = "#686868"
#
# [colors.bright]
# black = "#545454"
# red = "#909090"
# green = "#474747"
# yellow = "#4a4a4a"
# blue = "#5e5e5e"
# magenta = "#727272"
# cyan = "#cccccc"
# white = "#7c7c7c"
#
# [colors.primary]
# background = "#333333"
# foreground = "#9a9a9a"

# ### Light mode
# [colors.bright]
# black = "#aeaeae"
# blue = "#a4a4a4"
# cyan = "#333333"
# green = "#c2c2c2"
# magenta = "#909090"
# red = "#727272"
# white = "#868686"
# yellow = "#b8b8b8"
#
# [colors.normal]
# black = "#cccccc"
# blue = "#4a4a4a"
# cyan = "#545454"
# green = "#5e5e5e"
# magenta = "#474747"
# red = "#7c7c7c"
# white = "#9a9a9a"
# yellow = "#686868"
#
# [colors.primary]
# background = "#cccccc"
# foreground = "#9a9a9a"


[colors.primary]
background = "#DAD4BB"
foreground = "#787466"

[colors.cursor]
text = "#DAD4BB"
cursor = "#B26F5F"

[colors.selection]
text = "#DAD4BB"
background = "#5E6666"

[colors.normal]
black = "#787466"
red = "#CD664D"
green = "#727B59"
yellow = "#3BA99F"
blue = "#5E6666"
magenta = "#50403C"
cyan = "#4E4C43"
white = "#B9B49F"

[colors.bright]
black = "#898474"
red = "#D07C63"
green = "#878D6D"
yellow = "#5BB2A5"
blue = "#777C77"
magenta = "#6C5E55"
cyan = "#6A675B"
white = "#CAC4AD"

[colors.dim]
black = "#686458"
red = "#B9664F"
green = "#707659"
yellow = "#449B91"
blue = "#606663"
magenta = "#554742"
cyan = "#535147"
white = "#A9A491"

### Greyscale colours
# [colors.bright]
# black = "#888888"
# blue = "#9a9a9a"
# cyan = "#818181"
# green = "#aeaeae"
# magenta = "#5b5b5b"
# red = "#555555"
# white = "#ffffff"
# yellow = "#c1c1c1"
#
# [colors.normal]
# black = "#252525"
# blue = "#848484"
# cyan = "#979797"
# green = "#9b9b9b"
# magenta = "#6d6d6d"
# red = "#424242"
# white = "#fcfcfc"
# yellow = "#878787"
#
# [colors.primary]
# background = "#262626"
# foreground = "#c6c6c6"


#### Normal colours
# Faded colours
# [colors.bright]
# black = "#343434"
# blue = "#c9e6fd"
# cyan = "#ddfcf8"
# green = "#eff6ab"
# magenta = "#f7d7ff"
# red = "#ffc4c4"
# white = "#b5b5b5"
# yellow = "#ffe6b5"
#
# [colors.normal]
# black = "#262626"
# blue = "#8abae1"
# cyan = "#abebe2"
# green = "#c9d36a"
# magenta = "#db9fe9"
# red = "#ec8989"
# white = "#c6c6c6"
# yellow = "#ceb581"
#
# [colors.primary]
# background = "#262626"
# foreground = "#c6c6c6"
#
[font]
size = 12.0

[font.normal]
family = "Noto Sans Mono"
style = "Regular"
